### ISSUE TITLE
In Layer::autotiles, wrong coordinates used

### ISSUE THREAD

**Issue by InfiniteCoder01** [Bombfuse/ldtk_easy#1]
Function `Layer::autotiles`:
`
    pub fn autotiles(&self) -> Vec<Autotile> {
        self.inner
            .auto_layer_tiles
            .clone()
            .into_iter()
            .map(|instance| Autotile {
                source: (instance.src[0], instance.src[1]),
                pixel_position: (instance.px[0], instance.src[1]),
                flip: instance.f,
            })
            .collect()
    }
`
Should be:
`
    pub fn autotiles(&self) -> Vec<Autotile> {
        self.inner
            .auto_layer_tiles
            .clone()
            .into_iter()
            .map(|instance| Autotile {
                source: (instance.src[0], instance.src[1]),
                pixel_position: (instance.px[0], instance.px[1]),
                flip: instance.f,
            })
            .collect()
    }
`

**Comment by Bombfuse** [comment]
fix merged and version 0.1.5 pushed to crates.io
